apiVersion: v1
kind: Pod
metadata:
  name: frontend2
  labels:
    app: frontend
spec:
  containers:
    - image: varun3008/kubernetes_frontend
      name: frontend
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80