apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: frontend
  labels:
    app: frontend                                 # 2
spec:                                                # 3
  containers:
    - image: varun3008/kubernetes_frontend # 4
      name: frontend                              # 5
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80                          # 6