apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: frontend                                  # 6
    spec:
      containers:
        - image: varun3008/kubernetes_frontend
          imagePullPolicy: Never                         # 7
          name: frontend
          ports:
            - containerPort: 80
