apiVersion: v1
kind: Pod
metadata:
  name: config-map-pod-volume
spec:
  containers:
  - name: config-map-pod-volume
    image: busybox
    command: ["sh", "-c", "echo $(cat /etc/config/firstKey) && sleep 300;"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: test-configmap
  restartPolicy: Never
