apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: myapp
  namespace: test-namespace 
spec:
  containers:
  - name: app-controller
    image: busybox
    command: ['sh', '-c', 'echo Hello $(MY_VAR) && sleep 10']
    env:
    - name: MY_VAR
      value: kubernetes!
#  restartPolicy: Never
