apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: myapp
spec:
  containers:
  - name: nginx-controller
    image: nginx
    imagePullPolicy: Never
    ports:
      - containerPort: 80 
